# Generated by Django 2.1.7 on 2019-05-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_gists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gists',
            name='gist',
            field=models.CharField(max_length=100),
        ),
    ]
