# Generated by Django 2.1.7 on 2019-05-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gists',
            name='post',
        ),
        migrations.DeleteModel(
            name='Gists',
        ),
    ]
